permalink: /blog/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "node_modules"]
highlighter: rouge
markdown: kramdown

title : OctoPrint
tagline: Print anything from anywhere.

patreon: https://patreon.com/foosel
paypal: https://paypal.me/foosel/5
