permalink: /blog/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments
markdown: kramdown

title : OctoPrint
tagline: Print anything from anywhere.

